package nexora_backend.database.enums;

public enum NotificationType {
    REPORT_SUBMITTED,
    SOS_SUBMITTED,
    REPORT_VERIFIED,
    REPORT_ASSIGNED,
    TASK_ASSIGNED,
    TASK_ACCEPTED,
    TASK_DISPOSED,
    TASK_REJECTED,
    REPORT_COMPLETED,
    REPORT_REJECTED_BY_DEPT,
    ACCOUNT_CREATED,
    PASSWORD_RESET,
    DISASTER_MODE_ACTIVATED,
    REPORT_STATUS_UPDATED
}
